 Solve the linear system of equation A x = b, where A and b are given in the file msmatinv.txt
using both Jacobi and Gauss-Seidel iterative methods to a precision of 10e-5

# Gauss Seidel Method

In [34]:
A = [[-2 , 0 , 0, -1, 0 , 0.5], 
    [ 0,   4,    0.5,   0,    1,    0],
    [0 ,   0.5,  1.5 ,  0  ,  0  ,  0],
   [-1  ,  0  ,  0  ,  -2 ,   0 ,  1],
   [ 0   , 1 ,   0  ,   0  , -2.5 , 0],
    [ 0.5 , 0 ,   0   ,  1 ,   0 ,  -3.75]]

In [3]:
b

[-1, 0, 2.75, 2.5, -3, 2]

In [24]:
x1 = 0
x2 = 0
x3 = 0
x4 = 0
x5 =0
x6 =0

epsilon = 0.00001
converged = False


In [25]:
import numpy as np

In [28]:
x_old = np.array([x1, x2, x3, x4, x5 , x6])
print('Iteration results')
print(' k,    x1,    x2,    x3,    x4,     x5,  x6' )
for k in range(1, 50):
    x1 = (-1 + x4 - 0.5*x6)/-2
    x2 = (-x5-0.5*x3sol = jacobi(A,b,N=25,x=guess)
)/4
    x3 = (2.75-0.5*x2)/1.5
    x4 = (2.5 +x1 - x6)/-2
    x5 = (-3 - x2)/-2.5
    x6 = (2 - x4 - 0.5*x1)/-3.75
    x = np.array([x1, x2, x3, x4, x5, x6])
    # check if it is smaller than threshold
    dx = np.sqrt(np.dot(x-x_old, x-x_old))
    
    print("%d, %.4f, %.4f, %.4f, %.4f, %.4f, %.4f"%(k, x1, x2, x3, x4, x5, x6))
    if dx < epsilon:
        converged = True
        print('Converged!')
        break
        
    # assign the latest x value to the old value
    x_old = x

if not converged:
    print('Not converge, increase the # of iterations')

    
    
    
    
              

Iteration results
 k,    x1,    x2,    x3,    x4,     x5,  x6
1, 1.3544, -0.4983, 1.9994, -2.4183, 1.0007, -0.9976
2, 1.4598, -0.5001, 2.0000, -2.4787, 1.0000, -0.9997
3, 1.4894, -0.5000, 2.0000, -2.4946, 1.0000, -1.0000
4, 1.4973, -0.5000, 2.0000, -2.4986, 1.0000, -1.0000
5, 1.4993, -0.5000, 2.0000, -2.4997, 1.0000, -1.0000
6, 1.4998, -0.5000, 2.0000, -2.4999, 1.0000, -1.0000
7, 1.5000, -0.5000, 2.0000, -2.5000, 1.0000, -1.0000
8, 1.5000, -0.5000, 2.0000, -2.5000, 1.0000, -1.0000
9, 1.5000, -0.5000, 2.0000, -2.5000, 1.0000, -1.0000
Converged!


# Jacobi iterative method

In [51]:
from numpy import array, zeros, diag, diagflat, dot
from pprint import pprint


In [52]:
A =np.array([[-2 , 0 , 0, -1, 0 , 0.5], 
    [ 0,   4,    0.5,   0,    1,    0],
    [0 ,   0.5,  1.5 ,  0  ,  0  ,  0],
   [-1  ,  0  ,  0  ,  -2 ,   0 ,  1],
   [ 0   , 1 ,   0  ,   0  , -2.5 , 0],
    [ 0.5 , 0 ,   0   ,  1 ,   0 ,  -3.75]])

In [56]:
b = np.array([-1,  0,  2.75,  2.5, -3,  2])

In [57]:
def jacobi(A,b,N=25,x=None):
    """Solves the equation Ax=b via the Jacobi iterative method."""
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = np.zeros(len(A[0]))

    # Create a vector of the diagonal elements of A                                                                                                                                                
    # and subtract them from A                                                                                                                                                                     
    D = np.diag(A)
    R = A - np.diagflat(D)

    # Iterate for N times                                                                                                                                                                          
    for i in range(N):
        x = (b - np.dot(R,x)) / D
    return x

In [58]:
guess = np.array([1.0,1.0,1.0,1.0,1.0,1.0])

In [61]:
sol = jacobi(A,b,N=25,x=guess)
print ("A:")
pprint(A)

print ("b:")
pprint(b)

print ("x:")
pprint(sol)

A:
array([[-2.  ,  0.  ,  0.  , -1.  ,  0.  ,  0.5 ],
       [ 0.  ,  4.  ,  0.5 ,  0.  ,  1.  ,  0.  ],
       [ 0.  ,  0.5 ,  1.5 ,  0.  ,  0.  ,  0.  ],
       [-1.  ,  0.  ,  0.  , -2.  ,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  , -2.5 ,  0.  ],
       [ 0.5 ,  0.  ,  0.  ,  1.  ,  0.  , -3.75]])
b:
array([-1.  ,  0.  ,  2.75,  2.5 , -3.  ,  2.  ])
x:
array([ 1.49991255, -0.5       ,  2.        , -2.5000972 ,  1.        ,
       -0.99994705])
